<a href="https://colab.research.google.com/github/Manversajjad/Descritization-Binning/blob/main/Discretization_and_Binning_Comprehension_Stub_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Problem Statement

Let us go back to the job fair problem. As of now, you have cleaned the data and removed the duplicate entries.


Your task now is to discretize the values of the column etest_p into three quantiles, ['Low', 'Average', 'High'], and store the result in a new column, etest_c.


Transform the data based on the above conditions and answer these questions.

In [1]:
#Importing the library
import numpy as np
import pandas as pd

#Loading the data
hiring_data = pd.read_csv('/content/hiring_data.csv')

Perform the previous steps

In [2]:
#removing the rows that have more than four missing values
subset_df = hiring_data.dropna(thresh=5)
round(subset_df.salary.mean(),2)

#dropping duplicates
subset_df.drop_duplicates(inplace=True)
subset_df

#mapping values
map_label = {'S&T': 'Sci&Tech', 'C&M': 'Comm&Mgmt'}
subset_df.replace(map_label,inplace = True)
subset_df.head()

<ipython-input-2-190291195492>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df.drop_duplicates(inplace=True)
<ipython-input-2-190291195492>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df.replace(map_label,inplace = True)

,gender,degree_p,degree_b,workex,etest_p,specialization,mba_p,status,salary
0,M,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,127000.0
1,M,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,120000.0
2,M,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,125000.0
3,M,52.00,Sci&Tech,NaN,66.0,Mkt&HR,59.43,Not Placed,NaN
4,M,73.30,Comm&Mgmt,No,96.8,NaN,55.50,Placed,182500.0

In [3]:
hiring_data.head()

,gender,degree_p,degree_b,workex,etest_p,specialization,mba_p,status,salary
0,M,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,127000.0
1,M,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,120000.0
2,M,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,125000.0
3,M,52.00,Sci&Tech,NaN,66.0,Mkt&HR,59.43,Not Placed,NaN
4,M,73.30,Comm&Mgmt,No,96.8,NaN,55.50,Placed,182500.0

Use this data to answer the following questions

**Q1:**  Q1. How many students scored ‘High’ on the Employability test? [Hint: Use pd.qcut() to categorize the age groups into three quantiles.]


a)   33

b)   32

c)   31

d)   30

In [10]:
# Dropping rows with missing 'etest_p' values to ensure accurate quantile calculation
hiring_data_cleaned = hiring_data.dropna(subset=['etest_p'])

# Categorizing 'etest_p' into three quantiles: Low, Medium, and High
hiring_data_cleaned['etest_category'] = pd.qcut(hiring_data_cleaned['etest_p'],
                                                q=3,
                                                labels=['Low', 'Medium', 'High'])

# Counting the number of students in the 'High' category
high_category_count = hiring_data_cleaned[hiring_data_cleaned['etest_category'] == 'High'].shape[0]

high_category_count

<ipython-input-10-88caae493368>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hiring_data_cleaned['etest_category'] = pd.qcut(hiring_data_cleaned['etest_p'],

33

**Q2:** What is the total number of students who were placed even after scoring low on their employability test?

a) 22

b) 10

c) 32

d) 30

In [13]:
# write your code here
lowStillPlaced = hiring_data_cleaned[(hiring_data_cleaned['etest_category'] == 'Low') &( hiring_data_cleaned['status'] == 'Placed')].shape[0]
lowStillPlaced

22

**Q3:** What is the average salary of students who scored high on their employability test (rounded to 2 decimal places)?

a) 122004.35

b) 127517.65

c) 140385.19

d) 131533.82

In [14]:
# Filtering students who scored "High" on the employability test
High_scorers = hiring_data_cleaned[(hiring_data_cleaned['etest_category'] == 'High')]
# To calculate the average
Average_salary = High_scorers['salary'].mean()
# Round to 2 decimal places
Rounded_val_ofDecimals = round(Average_salary, 2)
Rounded_val_ofDecimals

140385.19

**Q4:** Fill in all the NaN values in the ‘salary’ column with the average salary of their respective quartile (e.g., the NaN salary of a student who scored low should be filled in with the average salary of all the students who scored low on the employability test). After filling in these values, what is the average salary of all the students?

a) 131533.82

b) 133982.07

c) 128898.01

d) 130442.65

In [16]:
# write your code here
# low_sal= round(subset_df[subset_df.etest_c == 'Low'].salary.mean(),2)

# avg_sal =round(subset_df[subset_df.etest_c == 'Average'].salary.mean(),2)

# high_sal = round(subset_df[subset_df.etest_c == 'High'].salary.mean(),2)

# subset_df.loc[subset_df.etest_c == 'Low','salary'] = subset_df.loc[subset_df.etest_c == 'Low'].salary.fillna(low_sal)

# subset_df.loc[subset_df.etest_c == 'High','salary'] = subset_df.loc[subset_df.etest_c == 'High'].salary.fillna(high_sal)

# subset_df.loc[subset_df.etest_c == 'Average','salary'] = subset_df.loc[subset_df.etest_c == 'Average'].salary.fillna(avg_sal)

# print("The average salary of all the students after filling the average salary of their respective quartile will be:", round(subset_df.salary.mean(),2))

# Grouping by 'etest_category' and calculating the average salary for each category
quartile_avg_salaries = hiring_data_cleaned.groupby('etest_category')['salary'].mean()

# Filling NaN values in 'salary' with the average salary of the respective quartile
hiring_data_cleaned['salary_filled'] = hiring_data_cleaned.apply(
    lambda row: quartile_avg_salaries[row['etest_category']] if pd.isnull(row['salary']) else row['salary'], axis=1
)

# Calculating the overall average salary after filling NaN values
overall_avg_salary = hiring_data_cleaned['salary_filled'].mean()

# Rounding to 2 decimal places
overall_avg_salary_rounded = round(overall_avg_salary, 2)

overall_avg_salary_rounded

<ipython-input-16-1c38f30316bd>:17: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  quartile_avg_salaries = hiring_data_cleaned.groupby('etest_category')['salary'].mean()
<ipython-input-16-1c38f30316bd>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hiring_data_cleaned['salary_filled'] = hiring_data_cleaned.apply(

130684.44