<a href="https://colab.research.google.com/github/Manversajjad/Descritization-Binning/blob/main/Video_game_sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import pandas as pd

In [9]:
vd = pd.read_csv(r'/content/video-game-sales.csv')
vd.head(5)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00

**Changing the RANK Index to match with the numbering of un-numbered Index**

In [3]:
vd.index = vd['Rank']
vd.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales
Rank,,,,,,,,,,
1,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46
2,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77
3,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31
4,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96
5,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00

Delete the Index RANK value to clean the data to perform the analysis unto.

In [4]:
del vd['Rank']
vd.head()

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales
Rank,,,,,,,,,
1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46
2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77
3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31
4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96
5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00

Explore the Distribution and Insights from the dataset

In [6]:
vd['Year'].describe()

count    16327.000000
mean      2006.406443
std          5.828981
min       1980.000000
25%       2003.000000
50%       2007.000000
75%       2010.000000
max       2020.000000
Name: Year, dtype: float64

Create Linearly Spaced Bins. To Analyze The Data Every 5 Year

In [11]:
bins_linear = np.linspace(start=1975, stop=2020, num=10)
bins_linear

array([1975., 1980., 1985., 1990., 1995., 2000., 2005., 2010., 2015.,
       2020.])

Bin the Year values based on previously created bins. When we cut the value, First Number or year will be excluded and will start from the next year onwards

In [14]:
vd['Year Bins'] = pd.cut(vd['Year'], bins_linear)
vd[['Name', 'Platform', 'Year', 'Year Bins']].head(10)

                        Name Platform    Year         Year Bins
0                 Wii Sports      Wii  2006.0  (2005.0, 2010.0]
1          Super Mario Bros.      NES  1985.0  (1980.0, 1985.0]
2             Mario Kart Wii      Wii  2008.0  (2005.0, 2010.0]
3          Wii Sports Resort      Wii  2009.0  (2005.0, 2010.0]
4   Pokemon Red/Pokemon Blue       GB  1996.0  (1995.0, 2000.0]
5                     Tetris       GB  1989.0  (1985.0, 1990.0]
6      New Super Mario Bros.       DS  2006.0  (2005.0, 2010.0]
7                   Wii Play      Wii  2006.0  (2005.0, 2010.0]
8  New Super Mario Bros. Wii      Wii  2009.0  (2005.0, 2010.0]
9                  Duck Hunt      NES  1984.0  (1980.0, 1985.0]

If wanted to see the number of counts in each Bins. We can use value_counts() function

In [15]:
vd['Year Bins'].value_counts().sort_index()

Year Bins
(1975.0, 1980.0]       9
(1980.0, 1985.0]     127
(1985.0, 1990.0]      85
(1990.0, 1995.0]     484
(1995.0, 2000.0]    1618
(2000.0, 2005.0]    3790
(2005.0, 2010.0]    6328
(2010.0, 2015.0]    3538
(2015.0, 2020.0]     348
Name: count, dtype: int64

Quick Descretization Data

In [16]:
vd['NA_Sales'].describe()

count    16598.000000
mean         0.264667
std          0.816683
min          0.000000
25%          0.000000
50%          0.080000
75%          0.240000
max         41.490000
Name: NA_Sales, dtype: float64

In [18]:
vd[vd['NA_Sales'] != 0]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Year Bins
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,"(2005.0, 2010.0]"
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,"(1980.0, 1985.0]"
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,"(2005.0, 2010.0]"
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,"(2005.0, 2010.0]"
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,"(1995.0, 2000.0]"
...,...,...,...,...,...,...,...,...,...,...,...
16591,16594,Myst IV: Revelation,PC,2004.0,Adventure,Ubisoft,0.01,0.00,0.00,0.00,"(2000.0, 2005.0]"
16592,16595,Plushees,DS,2008.0,Simulation,Destineer,0.01,0.00,0.00,0.00,"(2005.0, 2010.0]"
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,"(2000.0, 2005.0]"
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,"(2000.0, 2005.0]"
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,"(2000.0, 2005.0]"

Summarize the frequency of quartile Bins

In [20]:
pd.qcut(vd[vd['NA_Sales'] != 0]['NA_Sales'], 4).value_counts().sort_index()

NA_Sales
(0.009000000000000001, 0.06]    3174
(0.06, 0.14]                    3041
(0.14, 0.35]                    2937
(0.35, 41.49]                   2947
Name: count, dtype: int64

Summarize the frequency of decile bins, for north american sales of video games that have had sales. Keep in mind these values are defined to be in millions

In [21]:
pd.qcut(vd[vd['NA_Sales'] != 0]['NA_Sales'], 10).value_counts().sort_index()

NA_Sales
(0.009000000000000001, 0.03]    1624
(0.03, 0.05]                    1055
(0.05, 0.07]                     972
(0.07, 0.1]                     1271
(0.1, 0.14]                     1293
(0.14, 0.19]                    1060
(0.19, 0.28]                    1238
(0.28, 0.43]                    1169
(0.43, 0.8]                     1213
(0.8, 41.49]                    1204
Name: count, dtype: int64

Add Labels to help explain quantiles to end-users

In [24]:
Bins_label = ['Bronze', 'Silver', 'Gold', 'Platinum']
vd['Achievement_Level'] = pd.qcut(vd[vd['NA_Sales'] != 0]['NA_Sales'],q=4, labels=Bins_label)
vd.head(10)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Year Bins,Achievement_Level
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,"(2005.0, 2010.0]",Platinum
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,"(1980.0, 1985.0]",Platinum
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,"(2005.0, 2010.0]",Platinum
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,"(2005.0, 2010.0]",Platinum
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,"(1995.0, 2000.0]",Platinum
5,6,Tetris,GB,1989.0,Puzzle,Nintendo,23.20,2.26,4.22,0.58,"(1985.0, 1990.0]",Platinum
6,7,New Super Mario Bros.,DS,2006.0,Platform,Nintendo,11.38,9.23,6.50,2.90,"(2005.0, 2010.0]",Platinum
7,8,Wii Play,Wii,2006.0,Misc,Nintendo,14.03,9.20,2.93,2.85,"(2005.0, 2010.0]",Platinum
8,9,New Super Mario Bros. Wii,Wii,2009.0,Platform,Nintendo,14.59,7.06,4.70,2.26,"(2005.0, 2010.0]",Platinum
9,10,Duck Hunt,NES,1984.0,Shooter,Nintendo,26.93,0.63,0.28,0.47,"(1980.0, 1985.0]",Platinum

In [26]:
# Using iloc() function to determine the other variables in the bins by defined their index value
vd.iloc[10000:10100]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Year Bins,Achievement_Level
10000,10002,A Witch's Tale,DS,2009.0,Role-Playing,Nippon Ichi Software,0.08,0.00,0.03,0.01,"(2005.0, 2010.0]",Silver
10001,10003,Hollywood Squares,Wii,2010.0,Misc,Ubisoft,0.11,0.00,0.00,0.01,"(2005.0, 2010.0]",Silver
10002,10004,Cabela's Deer Hunt 2005 Season,XB,2004.0,Sports,Activision,0.09,0.02,0.00,0.00,"(2000.0, 2005.0]",Silver
10003,10005,SplashDown,XB,2002.0,Racing,Atari,0.09,0.02,0.00,0.00,"(2000.0, 2005.0]",Silver
10004,10006,Nobunaga no Yabou: Tenshoki,SAT,1995.0,Strategy,Tecmo Koei,0.00,0.00,0.11,0.00,"(1990.0, 1995.0]",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
10095,10097,JASF: Jane's Advanced Strike Fighters,PS3,2011.0,Simulation,Deep Silver,0.07,0.03,0.00,0.02,"(2010.0, 2015.0]",Silver
10096,10098,Cake Mania,DS,2007.0,Puzzle,Majesco Entertainment,0.09,0.01,0.00,0.01,"(2005.0, 2010.0]",Silver
10097,10099,Cold Fear,PS2,2005.0,Action,Ubisoft,0.06,0.04,0.00,0.01,"(2000.0, 2005.0]",Bronze
10098,10100,Akiba's Trip: Undead & Undressed,PS4,2014.0,Action,Acquire,0.08,0.00,0.01,0.02,"(2010.0, 2015.0]",Silver
10099,10101,Zangeki no Reginleiv,Wii,2010.0,Action,Nintendo,0.00,0.00,0.11,0.00,"(2005.0, 2010.0]",NaN